name: Run Termin Booking Leja

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:

jobs:
  book-termin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: npm install

      - name: Install Chromium browser
        run: sudo apt-get update && sudo apt-get install -y chromium-browser

      - name: Run Puppeteer script
        env:
          PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser
        run: node book-leja.js
