name: Run Termin Booking

on:
  schedule:
    - cron: '*/10 * * * *' # every 10 minutes
  workflow_dispatch:       # manual trigger from GitHub UI

jobs:
  book-termin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install Google Chrome
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer script
        run: node check-and-book.js
